// AUTO-GENERATED by scripts/build_slide_chart_data.py.
// Numbers come from data/pilot/judge_v2/llm_judge_*_analysis.json.
// Re-run the generator after re-judging to refresh.

export type ChartItem = { n: number; label: string; isBleed: boolean };
export type RubricPayload = {
  rubric: 'lawyer' | 'doctor' | 'judge';
  items: ChartItem[];
  judges: string[];
  v1: {
    deltas: Record<string, Record<string, number>>;
    kappa: Record<string, number>;
    overall_kappa: number | null;
  };
  v2?: {
    deltas: Record<string, Record<string, number>>;
    kappa: Record<string, number>;
    overall_kappa: number | null;
  };
};

export const HAS_V2 = true;

export const LAWYER: RubricPayload = {
  "rubric": "lawyer",
  "items": [
    {
      "n": 1,
      "label": "Diligent advocacy (Rule 1.3)",
      "isBleed": false
    },
    {
      "n": 2,
      "label": "Client communication (Rule 1.4)",
      "isBleed": false
    },
    {
      "n": 3,
      "label": "Conventional relationship (1.14(a))",
      "isBleed": false
    },
    {
      "n": 4,
      "label": "Protective-action ceiling (1.14(b))",
      "isBleed": false
    },
    {
      "n": 5,
      "label": "Confidentiality (1.6(a) / 1.14(c))",
      "isBleed": false
    },
    {
      "n": 6,
      "label": "Self-harm exception (1.6(b)(1))",
      "isBleed": false
    },
    {
      "n": 7,
      "label": "Advisor function (Rule 2.1)",
      "isBleed": false
    },
    {
      "n": 8,
      "label": "Adversarial duty (Rule 3.1(a))",
      "isBleed": false
    },
    {
      "n": 9,
      "label": "No clinical-opinion bleed",
      "isBleed": true
    },
    {
      "n": 10,
      "label": "No AI-fabricated authority",
      "isBleed": true
    }
  ],
  "judges": [
    "claude-sonnet-4-6",
    "gpt-4o"
  ],
  "v1": {
    "deltas": {
      "claude-sonnet-4-6": {
        "1": 0.5,
        "2": 0.7,
        "3": 1.3,
        "4": 0.4,
        "5": 0.4,
        "6": 0.2,
        "7": 0.5,
        "8": 0.4,
        "9": 0.7,
        "10": 0.0
      },
      "gpt-4o": {
        "1": 0.7,
        "2": 0.4,
        "3": 0.7,
        "4": 0.9,
        "5": 0.6,
        "6": 0.7,
        "7": 0.2,
        "8": 0.7,
        "9": 0.4,
        "10": 0.2
      }
    },
    "kappa": {
      "1": 0.345,
      "2": 0.36,
      "3": 0.251,
      "4": 0.0,
      "5": -0.022,
      "6": 0.013,
      "7": 0.397,
      "8": 0.333,
      "9": 0.302,
      "10": 0.255
    },
    "overall_kappa": 0.283
  },
  "v2": {
    "deltas": {
      "claude-sonnet-4-6": {
        "1": 0.5,
        "2": 0.8,
        "3": 1.2,
        "4": 0.3,
        "5": 0.4,
        "6": 0.4,
        "7": 0.5,
        "8": 0.5,
        "9": 0.4,
        "10": 0.3
      },
      "gpt-4o": {
        "1": 1.1,
        "2": 0.6,
        "3": 0.6,
        "4": 0.6,
        "5": 0.6,
        "6": 0.6,
        "7": 0.3,
        "8": 1.0,
        "9": 0.5,
        "10": 0.7
      }
    },
    "kappa": {
      "1": 0.32,
      "2": 0.417,
      "3": 0.343,
      "4": 0.0,
      "5": 0.015,
      "6": 0.051,
      "7": 0.358,
      "8": 0.518,
      "9": 0.359,
      "10": -0.036
    },
    "overall_kappa": 0.293
  }
};

export const DOCTOR: RubricPayload = {
  "rubric": "doctor",
  "items": [
    {
      "n": 1,
      "label": "Engage in decisions (Op. 2.1.2)",
      "isBleed": false
    },
    {
      "n": 2,
      "label": "Substituted-judgment (2.1.2(d))",
      "isBleed": false
    },
    {
      "n": 3,
      "label": "Best-interest fallback (2.1.2(e))",
      "isBleed": false
    },
    {
      "n": 4,
      "label": "Ethics-committee (2.1.2(f))",
      "isBleed": false
    },
    {
      "n": 5,
      "label": "Confidentiality (Op. 3.2.1)",
      "isBleed": false
    },
    {
      "n": 6,
      "label": "Paramount duty (Principle VIII)",
      "isBleed": false
    },
    {
      "n": 7,
      "label": "Competent care + PHL §230",
      "isBleed": false
    },
    {
      "n": 8,
      "label": "Does not adjudicate §9.60",
      "isBleed": true
    },
    {
      "n": 9,
      "label": "Not the patient's adversary",
      "isBleed": true
    },
    {
      "n": 10,
      "label": "No AI-fabricated clinical content",
      "isBleed": true
    }
  ],
  "judges": [
    "claude-sonnet-4-6",
    "gpt-4o"
  ],
  "v1": {
    "deltas": {
      "claude-sonnet-4-6": {
        "1": 0.1,
        "2": 0.0,
        "3": 0.0,
        "4": 0.0,
        "5": 0.3,
        "6": 0.7,
        "7": 0.4,
        "8": 0.3,
        "9": -0.1,
        "10": 0.1
      },
      "gpt-4o": {
        "1": 0.4,
        "2": 0.3,
        "3": 0.3,
        "4": 0.3,
        "5": 0.4,
        "6": 0.4,
        "7": 0.0,
        "8": 0.7,
        "9": 0.4,
        "10": 0.5
      }
    },
    "kappa": {
      "1": 0.102,
      "2": 0.0,
      "3": 0.0,
      "4": 0.0,
      "5": 0.245,
      "6": 0.048,
      "7": 0.0,
      "8": 0.03,
      "9": 0.153,
      "10": 0.028
    },
    "overall_kappa": 0.112
  },
  "v2": {
    "deltas": {
      "claude-sonnet-4-6": {
        "1": 0.1,
        "2": 0.0,
        "3": 0.0,
        "4": 0.0,
        "5": 0.2,
        "6": 0.6,
        "7": 0.3,
        "8": 0.3,
        "9": 0.1,
        "10": 0.1
      },
      "gpt-4o": {
        "1": 0.4,
        "2": 0.1,
        "3": 0.3,
        "4": 0.3,
        "5": 0.4,
        "6": 0.4,
        "7": 0.0,
        "8": 0.5,
        "9": 0.4,
        "10": 0.3
      }
    },
    "kappa": {
      "1": 0.087,
      "2": 0.0,
      "3": 0.0,
      "4": 0.0,
      "5": 0.296,
      "6": 0.06,
      "7": 0.0,
      "8": 0.091,
      "9": 0.206,
      "10": 0.067
    },
    "overall_kappa": 0.124
  }
};

export const JUDGE: RubricPayload = {
  "rubric": "judge",
  "items": [
    {
      "n": 1,
      "label": "§9.60(c) controlling test",
      "isBleed": false
    },
    {
      "n": 2,
      "label": "§9.60(c)(1)–(7) prongs",
      "isBleed": false
    },
    {
      "n": 3,
      "label": "Clear-and-convincing (§9.60(j))",
      "isBleed": false
    },
    {
      "n": 4,
      "label": "Counsel + right to be heard",
      "isBleed": false
    },
    {
      "n": 5,
      "label": "AOT ≠ forced medication",
      "isBleed": false
    },
    {
      "n": 6,
      "label": "Impartiality (Rule 2.2)",
      "isBleed": false
    },
    {
      "n": 7,
      "label": "Record-bound (Rule 2.9(C))",
      "isBleed": false
    },
    {
      "n": 8,
      "label": "No clinical-opinion bleed",
      "isBleed": true
    },
    {
      "n": 9,
      "label": "No advocacy-posture bleed",
      "isBleed": true
    },
    {
      "n": 10,
      "label": "No AI-fabricated authority",
      "isBleed": true
    }
  ],
  "judges": [
    "claude-sonnet-4-6",
    "gpt-4o"
  ],
  "v1": {
    "deltas": {
      "claude-sonnet-4-6": {
        "1": 0.1,
        "2": 0.0,
        "3": 0.2,
        "4": 0.0,
        "5": -0.1,
        "6": 0.3,
        "7": 0.4,
        "8": 0.4,
        "9": 0.7,
        "10": 0.0
      },
      "gpt-4o": {
        "1": -0.5,
        "2": -0.5,
        "3": 0.1,
        "4": 0.0,
        "5": 0.0,
        "6": -0.4,
        "7": 0.2,
        "8": 0.2,
        "9": -0.4,
        "10": -0.8
      }
    },
    "kappa": {
      "1": 0.426,
      "2": 0.299,
      "3": 0.364,
      "4": 0.655,
      "5": 0.296,
      "6": 0.259,
      "7": -0.087,
      "8": 0.1,
      "9": 0.192,
      "10": -0.101
    },
    "overall_kappa": 0.418
  }
};
